definition_version: 2
entities:
  iceberg_v3_demo_notebook:
    type: notebook
    query_warehouse: {{ demo_warehouse_name }}
    identifier:
      name: iceberg_v3_demo_notebook
      database: {{ demo_database_name }}
      schema: {{ demo_schema_name }}
    stage_path: {{ internal_named_stage }}
    notebook_file: {{ notebook_file_path }}
    artifacts:
    - {{ notebook_file }}
